# Generated by Django 4.1.2 on 2022-10-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='body',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
