# Generated by Django 4.1.2 on 2022-10-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texas_app', '0002_blogmodel_body_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(max_length=200),
        ),
    ]
