# Generated by Django 4.1.2 on 2022-10-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blogpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user',
            new_name='author',
        ),
    ]
