# Generated by Django 4.1.1 on 2022-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='post_body',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
