# Generated by Django 4.1.1 on 2022-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='post_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
