# Generated by Django 4.1.1 on 2022-09-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='post_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
