# Generated by Django 4.1.1 on 2022-09-28 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_mymodel_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
