# Generated by Django 4.1.1 on 2022-10-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShorterUrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_url', models.CharField(max_length=200)),
                ('shorter_url', models.CharField(max_length=200)),
            ],
        ),
    ]
