# Generated by Django 4.1.1 on 2022-10-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorterurlmodel',
            name='given_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shorterurlmodel',
            name='shorter_url',
            field=models.URLField(),
        ),
    ]
