# Generated by Django 4.1.1 on 2022-09-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_director_movie_genre_movie_in_theatres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='in_theatres',
            field=models.BooleanField(default=True),
        ),
    ]
