# Generated by Django 4.1.3 on 2022-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('have_watched', models.BooleanField(default=False)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
