# Generated by Django 4.1.3 on 2022-11-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='streaming',
        ),
    ]
