# Generated by Django 4.1.3 on 2022-11-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='onNetflix',
            field=models.BooleanField(blank=True),
        ),
    ]
