# Generated by Django 4.1.3 on 2022-11-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_owned_remove_movie_streaming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='metacritic',
        ),
    ]
