# Generated by Django 4.1.3 on 2022-11-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_onnetflix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='onAmazon',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='onHBO',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='onHulu',
            field=models.BooleanField(null=True),
        ),
    ]
