# Generated by Django 4.1.3 on 2022-11-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(height_field='504', upload_to='uploads/% Y/% m/% d/', width_field='378'),
        ),
    ]
