# Generated by Django 4.1.1 on 2022-10-01 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 1, 17, 14, 36, 842329)),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
