# Generated by Django 4.1.1 on 2022-09-30 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
