# Generated by Django 4.1.1 on 2022-10-01 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0002_groceryitem_completed_groceryitem_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.TextField(verbose_name=bool)),
            ],
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateField(default=datetime.date(2022, 9, 30)),
        ),
    ]
