# Generated by Django 4.1.1 on 2022-10-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0003_settings_alter_groceryitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
