# Generated by Django 4.1.1 on 2022-10-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='long_url',
            new_name='myfield',
        ),
    ]
