# Generated by Django 4.1.1 on 2022-10-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_rename_long_url_urlmodel_myfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='myfield',
            new_name='url_field',
        ),
    ]
