# Generated by Django 4.1.1 on 2022-10-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_rename_myfield_urlmodel_url_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmodel',
            old_name='url_field',
            new_name='long_url_field',
        ),
    ]
