# Generated by Django 4.1.1 on 2022-10-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_rename_url_field_urlmodel_long_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='short_url_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
