# Generated by Django 4.1.1 on 2022-10-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0006_urlmodel_url_name_alter_urlmodel_long_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='long_url_field',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='short_url_code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
