# Generated by Django 4.1.1 on 2022-10-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0008_alter_urlmodel_long_url_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='url_name',
        ),
    ]
