# Generated by Django 4.1.1 on 2022-10-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0009_remove_urlmodel_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='url_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
