# Generated by Django 4.1.1 on 2022-10-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0011_alter_urlmodel_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='long_url_field',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
