# Generated by Django 4.1.3 on 2022-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(height_field=500, null=True, upload_to='images/', width_field=500),
        ),
    ]
