# Generated by Django 4.1.1 on 2022-10-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='user',
            new_name='author',
        ),
    ]
