# Generated by Django 4.1.1 on 2022-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_user_blog_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='public',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
