# Generated by Django 4.1.1 on 2022-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blog_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
