# Generated by Django 4.1.1 on 2022-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groc_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='comp',
            field=models.BooleanField(default=False),
        ),
    ]
