# Generated by Django 4.1.3 on 2022-11-23 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='signup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
