# Generated by Django 4.1.1 on 2022-09-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('expiration_date', models.CharField(max_length=200)),
                ('in_cart', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
