# Generated by Django 4.1.1 on 2022-09-29 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='author',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='body',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
